<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BlogComment', 'doctrine');

/**
 * BaseBlogComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entry_id
 * @property text $body
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getEntryId()  Returns the current record's "entry_id" value
 * @method text        getBody()     Returns the current record's "body" value
 * @method BlogComment setId()       Sets the current record's "id" value
 * @method BlogComment setEntryId()  Sets the current record's "entry_id" value
 * @method BlogComment setBody()     Sets the current record's "body" value
 * 
 * @package    BLOG
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_comment');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('entry_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}