<?php

/**
 * BaseBlogComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entry_id
 * @property string $body
 * @property BlogEntry $BlogEntry
 * 
 * @method integer     getEntryId()   Returns the current record's "entry_id" value
 * @method string      getBody()      Returns the current record's "body" value
 * @method BlogEntry   getBlogEntry() Returns the current record's "BlogEntry" value
 * @method BlogComment setEntryId()   Sets the current record's "entry_id" value
 * @method BlogComment setBody()      Sets the current record's "body" value
 * @method BlogComment setBlogEntry() Sets the current record's "BlogEntry" value
 * 
 * @package    BLOG
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_comment');
        $this->hasColumn('entry_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogEntry', array(
             'local' => 'entry_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}