<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BlogEntry', 'doctrine');

/**
 * BaseBlogEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $title
 * @property text $body
 * 
 * @method integer   getId()    Returns the current record's "id" value
 * @method text      getTitle() Returns the current record's "title" value
 * @method text      getBody()  Returns the current record's "body" value
 * @method BlogEntry setId()    Sets the current record's "id" value
 * @method BlogEntry setTitle() Sets the current record's "title" value
 * @method BlogEntry setBody()  Sets the current record's "body" value
 * 
 * @package    BLOG
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_entry');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}