<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/22 14:45:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony;unix_socket=/var/run/mysqld/mysqld.sock;',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
