<?php

/**
 * BlogEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BLOG
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlogEntry extends BaseBlogEntry
{
	public function getComments(){
		return Doctrine_Query::create()
			->from('BlogComment c')
			->where('entry_id = ?', $this->getId())
			->execute();
	}
}
