<?php

/**
 * BlogEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogEntry');
    }
}