<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/27 11:12:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:../symfony.db',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
