BlogComment:
  connection: doctrine
  tableName: blog_comment
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    entry_id:
      type: integer(8)
      notnull: true
      primary: false
      autoincrement: false
    body:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
BlogEntry:
  connection: doctrine
  tableName: blog_entry
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    title:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
    body:
      type: text()
      notnull: true
      primary: false
      autoincrement: false
